### ISSUE TITLE
question about Texture Extraction

### ISSUE THREAD

**Issue by tianty** [XuanchenLi/Topo4D#2]
Congratulations on your job being accepted by eccv！

I have some questions about Texture Extraction. For the densified Gaussian mesh Gt', it is easy to map the color attributes of each Gaussian to the texture map through UV. But even after NxN densification, the number of Gaussians is still less than the number of pixels. How do you deal with the other pixels that are missing from UV mapping? And you mentioned in the paper that "Since our Gaussian meshes are topologized, we can triangulate them and map learned dense texture colors to texture maps {Mi}F−1 i=0 by a rasterization-based forward rendering method [34]." What specific operations do you refer to for completing the complete texture?

**Comment by XuanchenLi** [comment]
Hello, thank you for your attention. If you set N = 30, the number of pixels is approximately 5 times the number of Gaussians. We observed that such density is sufficient for 8K textures. The pixel color is obtained by interpolating the colors of Gaussians that form the triangle which covers the pixel, similar to traditional rasterization rendering. I believe this repo can help you: https://github.com/yfeng95/face3d

**Comment by tianty** [comment]
> Hello, thank you for your attention. If you set N = 30, the number of pixels is approximately 5 times the number of Gaussians. We observed that such density is sufficient for 8K textures. The pixel color is obtained by interpolating the colors of Gaussians that form the triangle which covers the pixel, similar to traditional rasterization rendering. I believe this repo can help you: https://github.com/yfeng95/face3d

After 30x30 densification, the number of Gaussians reaches more than 10 million, which is 4~5 times the number of pixels in 8K maps. This can indeed be supplemented by interpolation to fill in the pixels of the missing UV mapping. I noticed that the topology and UV used are similar to metahuman. For the top of the head (the area covered by the hairnet), eyeballs, and mouth, are masks used for filling and filtering in the map?

**Comment by XuanchenLi** [comment]
We perform alpha blending on the generated textures and a template texture to fill the invisible areas and remove redundant areas. It is a common practice in the industry.
