### ISSUE TITLE
Detailed formula derivation of Gaussian Normal Expansion in supplementary material

### ISSUE THREAD

**Issue by shanzhajuan** [XuanchenLi/Topo4D#3]
Regarding vertex normal offset, my understanding is to find the distance from the center to the edge of a Gaussian ellipsoid in the normal direction. Then multiply this distance by the normal vector and add it to the center of the Gaussian ellipsoid. The specific calculation formulas are given in formulas (a) and (b) in the supplementary material. How is this derived? What does multiplying the vertex normal by R^-1 represent? The paper mentions projection distance. How is this represented?

**Comment by XuanchenLi** [comment]
The scale of Gaussians extends the rendering boundary to the real surface. Therefore, we set the Gaussian offset with the scale in normal directions, i.e. the projection distance mentioned in the paper. Multiplying the vertex normal by R^-1 is just for the convenience of calculating this distance. We observed that this expansion operation increases geometric accuracy by about 0.1mm.

**Comment by shanzhajuan** [comment]
> The scale of Gaussians extends the rendering boundary to the real surface. Therefore, we set the Gaussian offset with the scale in normal directions, i.e. the projection distance mentioned in the paper. Multiplying the vertex normal by R^-1 is just for the convenience of calculating this distance. We observed that this expansion operation increases geometric accuracy by about 0.1mm.

Is there a more detailed explanation or derivation of formula (b)? Especially the term under the square root, which I guess represents the projection distance. Thank you for providing me with more explanation.

**Comment by XuanchenLi** [comment]
Formula (a) performs coordinate transformation on the normal vector. Formula (b) calculates the distance from the origin to the surface of the ellipsoid based on the transformed direction vector. 
![formula](https://github.com/user-attachments/assets/510accb8-08fe-4e8e-b00a-ed84045a991c)
