### ISSUE TITLE
question about dense mesh optmization

### ISSUE THREAD

**Issue by wasahaiah** [XuanchenLi/Topo4D#4]
when I run "python train.py --input_dir test/videos_low --output_dir output --exp exp_op_dense --seq seq_01 --dense_input_dir test/videos --gen_tex --tex_res 8192" ,
there exit two bugs:
1. KeyError: 'first_frame_attributes', I solve it by move "initialize_post_first_timestep" above "if args.gen_tex";
2.  "KeyError: 'dense_vertex_normals'" . For this error, I cannot solve. Would you please check and solve this bug?

**Comment by XuanchenLi** [comment]
Sorry for the issues in the code. I have fixed these bugs. You can try it again.
Please let me know if you have more problems.

**Comment by wasahaiah** [comment]
> Sorry for the issues in the code. I have fixed these bugs. You can try it again. Please let me know if you have more problems.

Thanks for your replay so quickly and release the source code, it really help me a lot. As you say, there exists several small bugs (but they are easily fixed). I advice to run the code and fixed them.

**Comment by dklee98** [comment]
Hello @wasahaiah

I’m the original author/maintainer of TRG-Planner. I noticed your repository is a fork of the original project.

I previously sent you an email (via your contact email: [wangnzhou@sina.com](mailto:wangnzhou@sina.com)) regarding an urgent and important matter related to this repository, but I haven’t heard back yet.
Could you please check it and reply when you get a chance?

In addition, I’ve opened a pull request on your repository related to this matter (https://github.com/wasahaiah/TRG-planner)
When you have time, I would appreciate it if you could also take a look at the PR and let me know your thoughts.

If your email is not available, please let me know other contact information.
You can also reach me at: [dklee@urobotics.ai](mailto:dklee@urobotics.ai)

Thank you for your time and cooperation.
