### ISSUE TITLE
How to train using triangle meshes?

### ISSUE THREAD

**Issue by pratch** [XuanchenLi/Topo4D#7]
I notice that the train code states that "we only densify the quad faces for convenience". And when I tried using a triangle mesh, I ran into "indices must be integer/boolean" error at `helpers.py` code that does `attribute[quad_faces[vertex_father].squeeze(1)]`.

Is there a way to make triangle mesh work, or is this method only limited to quad meshes?

**Comment by XuanchenLi** [comment]
Yes, the current densification method only supports quad faces, for we operate UV-space densification through bilinear interpolation. If you want to use a triangle mesh, you need to change it to a triangle interpolation method.
﻿
I would suggest that you transfer your topology to ours by softwares like [Wrap](https://faceform.com/).

**Comment by pratch** [comment]
Thank you for the quick reply! I tried using Wrap per your suggestion to transfer topology using the "MatchTopology" block, but was unsuccessful as it complains that the two meshes have different maximum vertex degree.

If I were to try to use my own topology, what tool or code can I use to generate the facial region partition .pkl? Was it done manually by hand?

**Comment by XuanchenLi** [comment]
We manually build the facial partition.
You can use the 'wrapping' block to transfer your topology, please refer to the image or the [official document.](https://docs.faceform.com/Wrap/index.html)
![微信截图_20241216143516](https://github.com/user-attachments/assets/5445692d-400d-4546-a4a6-ba292e83fd74)
